### ISSUE TITLE
CT required tandems must be supplied

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/graphing-quadratics#136]
```
graphing-quadratics : phet-io-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599640382837/graphing-quadratics/graphing-quadratics_en.html?continuousTest=%7B%22test%22%3A%5B%22graphing-quadratics%22%2C%22phet-io-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1599640382837%22%2C%22timestamp%22%3A1599641185374%7D&ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Query: ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: required tandems must be supplied
Error: Assertion failed: required tandems must be supplied
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599640382837/assert/js/assert.js:22:13)
at Action.initializePhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599640382837/tandem/js/PhetioObject.js:240:17)
at new PhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599640382837/tandem/js/PhetioObject.js:189:10)
at new Action (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599640382837/axon/js/Action.js:92:5)
at new PressListener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599640382837/scenery/js/listeners/PressListener.js:245:23)
at new Manipulator (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599640382837/graphing-lines/js/common/view/manipulator/Manipulator.js:62:29)
at new GQManipulator (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599640382837/graphing-quadratics/js/common/view/GQManipulator.js:54:5)
at new VertexManipulator (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599640382837/graphing-quadratics/js/common/view/VertexManipulator.js:80:5)
at new VertexFormGraphNode (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599640382837/graphing-quadratics/js/vertexform/view/VertexFormGraphNode.js:36:31)
at new VertexFormScreenView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599640382837/graphing-quadratics/js/vertexform/view/VertexFormScreenView.js:36:7)
id: Bayes Chrome
Snapshot from 9/9/2020, 2:33:02 AM

----------------------------------

graphing-quadratics : phet-io-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599640382837/graphing-quadratics/graphing-quadratics_en.html?continuousTest=%7B%22test%22%3A%5B%22graphing-quadratics%22%2C%22phet-io-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1599640382837%22%2C%22timestamp%22%3A1599654263616%7D&ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Query: ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: required tandems must be supplied
Error: Assertion failed: required tandems must be supplied
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599640382837/assert/js/assert.js:22:13)
at Action.initializePhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599640382837/tandem/js/PhetioObject.js:240:17)
at new PhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599640382837/tandem/js/PhetioObject.js:189:10)
at new Action (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599640382837/axon/js/Action.js:92:5)
at new PressListener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599640382837/scenery/js/listeners/PressListener.js:245:23)
at new Manipulator (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599640382837/graphing-lines/js/common/view/manipulator/Manipulator.js:62:29)
at new GQManipulator (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599640382837/graphing-quadratics/js/common/view/GQManipulator.js:54:5)
at new VertexManipulator (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599640382837/graphing-quadratics/js/common/view/VertexManipulator.js:80:5)
at new VertexFormGraphNode (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599640382837/graphing-quadratics/js/vertexform/view/VertexFormGraphNode.js:36:31)
at new VertexFormScreenView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599640382837/graphing-quadratics/js/vertexform/view/VertexFormScreenView.js:36:7)
id: Bayes Chrome
Snapshot from 9/9/2020, 2:33:02 AM

----------------------------------

graphing-quadratics : phet-io-mirror-inputs-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599640382837/phet-io-wrappers/mirror-inputs/?sim=graphing-quadratics&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22graphing-quadratics%22%2C%22phet-io-mirror-inputs-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1599640382837%22%2C%22timestamp%22%3A1599641860711%7D
Uncaught Error: Uncaught Error: Assertion failed: required tandems must be supplied
Error: Assertion failed: required tandems must be supplied
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599640382837/assert/js/assert.js:22:13)
at Action.initializePhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599640382837/tandem/js/PhetioObject.js:240:17)
at new PhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599640382837/tandem/js/PhetioObject.js:189:10)
at new Action (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599640382837/axon/js/Action.js:92:5)
at new PressListener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599640382837/scenery/js/listeners/PressListener.js:245:23)
at new Manipulator (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599640382837/graphing-lines/js/common/view/manipulator/Manipulator.js:62:29)
at new GQManipulator (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599640382837/graphing-quadratics/js/common/view/GQManipulator.js:54:5)
at new VertexManipulator (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599640382837/graphing-quadratics/js/common/view/VertexManipulator.js:80:5)
at new VertexFormGraphNode (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599640382837/graphing-quadratics/js/vertexform/view/VertexFormGraphNode.js:36:31)
at new VertexFormScreenView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599640382837/graphing-quadratics/js/vertexform/view/VertexFormScreenView.js:36:7)
id: Bayes Chrome
Snapshot from 9/9/2020, 2:33:02 AM

----------------------------------

graphing-quadratics : phet-io-mirror-inputs-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599640382837/phet-io-wrappers/mirror-inputs/?sim=graphing-quadratics&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22graphing-quadratics%22%2C%22phet-io-mirror-inputs-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1599640382837%22%2C%22timestamp%22%3A1599652823090%7D
Uncaught Error: Uncaught Error: Assertion failed: required tandems must be supplied
Error: Assertion failed: required tandems must be supplied
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599640382837/assert/js/assert.js:22:13)
at Action.initializePhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599640382837/tandem/js/PhetioObject.js:240:17)
at new PhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599640382837/tandem/js/PhetioObject.js:189:10)
at new Action (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599640382837/axon/js/Action.js:92:5)
at new PressListener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599640382837/scenery/js/listeners/PressListener.js:245:23)
at new Manipulator (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599640382837/graphing-lines/js/common/view/manipulator/Manipulator.js:62:29)
at new GQManipulator (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599640382837/graphing-quadratics/js/common/view/GQManipulator.js:54:5)
at new VertexManipulator (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599640382837/graphing-quadratics/js/common/view/VertexManipulator.js:80:5)
at new VertexFormGraphNode (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599640382837/graphing-quadratics/js/vertexform/view/VertexFormGraphNode.js:36:31)
at new VertexFormScreenView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599640382837/graphing-quadratics/js/vertexform/view/VertexFormScreenView.js:36:7)
id: Bayes Chrome
Snapshot from 9/9/2020, 2:33:02 AM

----------------------------------

graphing-quadratics : phet-io-state-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599640382837/phet-io-wrappers/state/?sim=graphing-quadratics&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22graphing-quadratics%22%2C%22phet-io-state-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1599640382837%22%2C%22timestamp%22%3A1599641532754%7D
Uncaught Error: Uncaught Error: Assertion failed: required tandems must be supplied
Error: Assertion failed: required tandems must be supplied
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599640382837/assert/js/assert.js:22:13)
at Action.initializePhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599640382837/tandem/js/PhetioObject.js:240:17)
at new PhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599640382837/tandem/js/PhetioObject.js:189:10)
at new Action (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599640382837/axon/js/Action.js:92:5)
at new PressListener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599640382837/scenery/js/listeners/PressListener.js:245:23)
at new Manipulator (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599640382837/graphing-lines/js/common/view/manipulator/Manipulator.js:62:29)
at new GQManipulator (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599640382837/graphing-quadratics/js/common/view/GQManipulator.js:54:5)
at new VertexManipulator (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599640382837/graphing-quadratics/js/common/view/VertexManipulator.js:80:5)
at new VertexFormGraphNode (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599640382837/graphing-quadratics/js/vertexform/view/VertexFormGraphNode.js:36:31)
at new VertexFormScreenView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599640382837/graphing-quadratics/js/vertexform/view/VertexFormScreenView.js:36:7)
id: Bayes Chrome
Snapshot from 9/9/2020, 2:33:02 AM

----------------------------------

graphing-quadratics : phet-io-state-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599640382837/phet-io-wrappers/state/?sim=graphing-quadratics&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22graphing-quadratics%22%2C%22phet-io-state-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1599640382837%22%2C%22timestamp%22%3A1599653019975%7D
Uncaught Error: Uncaught Error: Assertion failed: required tandems must be supplied
Error: Assertion failed: required tandems must be supplied
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599640382837/assert/js/assert.js:22:13)
at Action.initializePhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599640382837/tandem/js/PhetioObject.js:240:17)
at new PhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599640382837/tandem/js/PhetioObject.js:189:10)
at new Action (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599640382837/axon/js/Action.js:92:5)
at new PressListener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599640382837/scenery/js/listeners/PressListener.js:245:23)
at new Manipulator (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599640382837/graphing-lines/js/common/view/manipulator/Manipulator.js:62:29)
at new GQManipulator (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599640382837/graphing-quadratics/js/common/view/GQManipulator.js:54:5)
at new VertexManipulator (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599640382837/graphing-quadratics/js/common/view/VertexManipulator.js:80:5)
at new VertexFormGraphNode (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599640382837/graphing-quadratics/js/vertexform/view/VertexFormGraphNode.js:36:31)
at new VertexFormScreenView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599640382837/graphing-quadratics/js/vertexform/view/VertexFormScreenView.js:36:7)
id: Bayes Chrome
Snapshot from 9/9/2020, 2:33:02 AM

----------------------------------

graphing-quadratics : phet-io-studio-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599640382837/studio/?sim=graphing-quadratics&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22graphing-quadratics%22%2C%22phet-io-studio-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1599640382837%22%2C%22timestamp%22%3A1599641189452%7D
Uncaught Error: Uncaught Error: Assertion failed: required tandems must be supplied
Error: Assertion failed: required tandems must be supplied
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599640382837/assert/js/assert.js:22:13)
at Action.initializePhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599640382837/tandem/js/PhetioObject.js:240:17)
at new PhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599640382837/tandem/js/PhetioObject.js:189:10)
at new Action (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599640382837/axon/js/Action.js:92:5)
at new PressListener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599640382837/scenery/js/listeners/PressListener.js:245:23)
at new Manipulator (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599640382837/graphing-lines/js/common/view/manipulator/Manipulator.js:62:29)
at new GQManipulator (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599640382837/graphing-quadratics/js/common/view/GQManipulator.js:54:5)
at new VertexManipulator (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599640382837/graphing-quadratics/js/common/view/VertexManipulator.js:80:5)
at new VertexFormGraphNode (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599640382837/graphing-quadratics/js/vertexform/view/VertexFormGraphNode.js:36:31)
at new VertexFormScreenView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599640382837/graphing-quadratics/js/vertexform/view/VertexFormScreenView.js:36:7)
id: Bayes Chrome
Snapshot from 9/9/2020, 2:33:02 AM

----------------------------------

graphing-quadratics : phet-io-studio-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599640382837/studio/?sim=graphing-quadratics&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22graphing-quadratics%22%2C%22phet-io-studio-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1599640382837%22%2C%22timestamp%22%3A1599654006016%7D
Uncaught Error: Uncaught Error: Assertion failed: required tandems must be supplied
Error: Assertion failed: required tandems must be supplied
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599640382837/assert/js/assert.js:22:13)
at Action.initializePhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599640382837/tandem/js/PhetioObject.js:240:17)
at new PhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599640382837/tandem/js/PhetioObject.js:189:10)
at new Action (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599640382837/axon/js/Action.js:92:5)
at new PressListener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599640382837/scenery/js/listeners/PressListener.js:245:23)
at new Manipulator (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599640382837/graphing-lines/js/common/view/manipulator/Manipulator.js:62:29)
at new GQManipulator (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599640382837/graphing-quadratics/js/common/view/GQManipulator.js:54:5)
at new VertexManipulator (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599640382837/graphing-quadratics/js/common/view/VertexManipulator.js:80:5)
at new VertexFormGraphNode (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599640382837/graphing-quadratics/js/vertexform/view/VertexFormGraphNode.js:36:31)
at new VertexFormScreenView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599640382837/graphing-quadratics/js/vertexform/view/VertexFormScreenView.js:36:7)
id: Bayes Chrome
Snapshot from 9/9/2020, 2:33:02 AM

----------------------------------

graphing-quadratics : phet-io-wrappers-tests : assert
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599640382837/phet-io-wrappers/phet-io-wrappers-tests.html?sim=graphing-quadratics&phetioDebug
3 out of 4 tests passed. 1 failed.
SimTests: graphing-quadratics: iframe api failed:
Uncaught Error: Uncaught Error: Assertion failed: required tandems must be supplied
Error: Assertion failed: required tandems must be supplied
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599640382837/assert/js/assert.js:22:13)
at Action.initializePhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599640382837/tandem/js/PhetioObject.js:240:17)
at new PhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599640382837/tandem/js/PhetioObject.js:189:10)
at new Action (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599640382837/axon/js/Action.js:92:5)
at new PressListener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599640382837/scenery/js/listeners/PressListener.js:245:23)
at new Manipulator (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599640382837/graphing-lines/js/common/view/manipulator/Manipulator.js:62:29)
at new GQManipulator (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599640382837/graphing-quadratics/js/common/view/GQManipulator.js:54:5)
at new VertexManipulator (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599640382837/graphing-quadratics/js/common/view/VertexManipulator.js:80:5)
at new VertexFormGraphNode (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599640382837/graphing-quadratics/js/vertexform/view/VertexFormGraphNode.js:36:31)
at new VertexFormScreenView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599640382837/graphing-quadratics/js/vertexform/view/VertexFormScreenView.js:36:7)

Did not complete in 200000ms, may not have completed all tests
id: Bayes Chrome
Snapshot from 9/9/2020, 2:33:02 AM
```

**Comment by pixelzoom** [comment]
Regression occurred in https://github.com/phetsims/graphing-lines/issues/132 when converting to PressListener, which has Tandem.REQUIRED.  I needed to addd `tandem: Tandem.OPT_OUT`.

Closing.
