### ISSUE TITLE
CT: Breaking API changes detected

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/graphing-quadratics#150]
This is happening because we're making incremental improvements to the sim as part of PhET-iO redesign.  The changes are desired.  I don't know how to deal with this, and I'm looking for guidance in https://github.com/phetsims/chipper/issues/1023. @samreid @zepumph FYI.

```
graphing-quadratics : phet-io-api-compatibility : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1616082139562/graphing-quadratics/graphing-quadratics_en.html?continuousTest=%7B%22test%22%3A%5B%22graphing-quadratics%22%2C%22phet-io-api-compatibility%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1616082139562%22%2C%22timestamp%22%3A1616083270647%7D&ea&brand=phet-io&phetioStandalone&phetioCreateArchetypes&phetioCompareAPI
Query: ea&brand=phet-io&phetioStandalone&phetioCreateArchetypes&phetioCompareAPI
Uncaught Error: Assertion failed: Breaking API changes detected, please roll them back or revise the reference API:

graphingQuadratics.focusAndDirectrixScreen.view.focusManipulator.visibleProperty.phetioTypeName changed from PropertyIO<BooleanIO> to DerivedPropertyIO<BooleanIO>
graphingQuadratics.focusAndDirectrixScreen.view.vertexManipulator.visibleProperty.phetioTypeName changed from PropertyIO<BooleanIO> to DerivedPropertyIO<BooleanIO>
graphingQuadratics.standardFormScreen.view.noRealRootsNode.visibleProperty.phetioTypeName changed from PropertyIO<BooleanIO> to DerivedPropertyIO<BooleanIO>
graphingQuadratics.standardFormScreen.view.rootsNode.visibleProperty.phetioTypeName changed from PropertyIO<BooleanIO> to DerivedPropertyIO<BooleanIO>
graphingQuadratics.standardFormScreen.view.vertexNode.visibleProperty.phetioTypeName changed from PropertyIO<BooleanIO> to DerivedPropertyIO<BooleanIO>
graphingQuadratics.vertexFormScreen.view.vertexManipulator.visibleProperty.phetioTypeName changed from PropertyIO<BooleanIO> to DerivedPropertyIO<BooleanIO>
Error: Assertion failed: Breaking API changes detected, please roll them back or revise the reference API:

graphingQuadratics.focusAndDirectrixScreen.view.focusManipulator.visibleProperty.phetioTypeName changed from PropertyIO<BooleanIO> to DerivedPropertyIO<BooleanIO>
graphingQuadratics.focusAndDirectrixScreen.view.vertexManipulator.visibleProperty.phetioTypeName changed from PropertyIO<BooleanIO> to DerivedPropertyIO<BooleanIO>
graphingQuadratics.standardFormScreen.view.noRealRootsNode.visibleProperty.phetioTypeName changed from PropertyIO<BooleanIO> to DerivedPropertyIO<BooleanIO>
graphingQuadratics.standardFormScreen.view.rootsNode.visibleProperty.phetioTypeName changed from PropertyIO<BooleanIO> to DerivedPropertyIO<BooleanIO>
graphingQuadratics.standardFormScreen.view.vertexNode.visibleProperty.phetioTypeName changed from PropertyIO<BooleanIO> to DerivedPropertyIO<BooleanIO>
graphingQuadratics.vertexFormScreen.view.vertexManipulator.visibleProperty.phetioTypeName changed from PropertyIO<BooleanIO> to DerivedPropertyIO<BooleanIO>
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1616082139562/assert/js/assert.js:25:13)
at XMLHttpRequest.<anonymous> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1616082139562/phet-io/js/phetioEngine.js:264:23)
id: Bayes Chrome
Snapshot from 3/18/2021, 9:42:19 AM
```

**Comment by samreid** [comment]
I added a note at https://github.com/phetsims/chipper/issues/1023#issuecomment-802106151

**Comment by pixelzoom** [comment]
Fixed in https://github.com/phetsims/phet-io/commit/ca12876ef5ade5d76d106484d42c3c65283e4bb4, closing.
