### ISSUE TITLE
Failure to grunt

### ISSUE THREAD

**Issue by lmulhall-phet** [phetsims/graphing-quadratics#5]
```
graphing-quadratics : build : phet
Failure to grunt snapshot-1531167556397/graphing-quadratics:
Running "lint-all" task

Running "clean" task

Running "build" task
Building runnable repository (graphing-quadratics, brands: phet)
Building brand: phet
Fatal error: Perennial task failed:
Error: Error: Error: ENOENT: no such file or directory, open '/data/share/phet/continuous-testing/snapshot-1531167556397/graphing-quadratics/js/standardForm/model/StandardFormModel.js'
In module tree:
    graphing-quadratics-main
      GRAPHING_QUADRATICS/standardform/StandardFormScreen

  at /data/share/phet/continuous-testing/snapshot-1531167556397/chipper/js/grunt/requireBuild.js:107:15
  at /data/share/phet/continuous-testing/snapshot-1531167556397/chipper/node_modules/requirejs/bin/r.js:3059:39
  at /data/share/phet/continuous-testing/snapshot-1531167556397/chipper/node_modules/requirejs/bin/r.js:2999:25
  at Function.prim.nextTick (/data/share/phet/continuous-testing/snapshot-1531167556397/chipper/node_modules/requirejs/bin/r.js:28077:9)
  at Object.errback (/data/share/phet/continuous-testing/snapshot-1531167556397/chipper/node_modules/requirejs/bin/r.js:2998:26)
  at Object.callback (/data/share/phet/continuous-testing/snapshot-1531167556397/chipper/node_modules/requirejs/bin/r.js:2984:23)
  at Object.then (/data/share/phet/continuous-testing/snapshot-1531167556397/chipper/node_modules/requirejs/bin/r.js:3038:23)
  at runBuild (/data/share/phet/continuous-testing/snapshot-1531167556397/chipper/node_modules/requirejs/bin/r.js:30291:48)
  at Object.execCb (/data/share/phet/continuous-testing/snapshot-1531167556397/chipper/node_modules/requirejs/bin/r.js:1946:33)
  at Module.check (/data/share/phet/continuous-testing/snapshot-1531167556397/chipper/node_modules/requirejs/bin/r.js:1133:51)
  at Module.<anonymous> (/data/share/phet/continuous-testing/snapshot-1531167556397/chipper/node_modules/requirejs/bin/r.js:1389:34)
  at /data/share/phet/continuous-testing/snapshot-1531167556397/chipper/node_modules/requirejs/bin/r.js:384:23
  at /data/share/phet/continuous-testing/snapshot-1531167556397/chipper/node_modules/requirejs/bin/r.js:1439:21
  at each (/data/share/phet/continuous-testing/snapshot-1531167556397/chipper/node_modules/requirejs/bin/r.js:309:31)
  at Module.emit (/data/share/phet/continuous-testing/snapshot-1531167556397/chipper/node_modules/requirejs/bin/r.js:1438:17)
  at Module.check (/data/share/phet/continuous-testing/snapshot-1531167556397/chipper/node_modules/requirejs/bin/r.js:1188:30)
  at Module.enable (/data/share/phet/continuous-testing/snapshot-1531167556397/chipper/node_modules/requirejs/bin/r.js:1426:22)
  at Module.init (/data/share/phet/continuous-testing/snapshot-1531167556397/chipper/node_modules/requirejs/bin/r.js:1038:26)
  at Module.<anonymous> (/data/share/phet/continuous-testing/snapshot-1531167556397/chipper/node_modules/requirejs/bin/r.js:1264:30)
  at /data/share/phet/continuous-testing/snapshot-1531167556397/chipper/node_modules/requirejs/bin/r.js:384:23
  at /data/share/phet/continuous-testing/snapshot-1531167556397/chipper/node_modules/requirejs/bin/r.js:2697:17
  at Object.execCb (/data/share/phet/continuous-testing/snapshot-1531167556397/chipper/node_modules/requirejs/bin/r.js:1946:33)
  at Module.check (/data/share/phet/continuous-testing/snapshot-1531167556397/chipper/node_modules/requirejs/bin/r.js:1133:51)
  at Module.enable (/data/share/phet/continuous-testing/snapshot-1531167556397/chipper/node_modules/requirejs/bin/r.js:1426:22)
  at Module.init (/data/share/phet/continuous-testing/snapshot-1531167556397/chipper/node_modules/requirejs/bin/r.js:1038:26)
  at /data/share/phet/continuous-testing/snapshot-1531167556397/chipper/node_modules/requirejs/bin/r.js:1710:36
  at _combinedTickCallback (internal/process/next_tick.js:131:7)
  at process._tickCallback (internal/process/next_tick.js:180:9)

Full Error details:
{}


Approximately 7/9/2018, 2:19:16 PM
```

I think related to https://github.com/phetsims/graphing-quadratics/commit/06aebec5187340dec9c64b9ddd937c7af6ea0929.

**Comment by pixelzoom** [comment]
My bad.  This built fine on macOS when I tested it, but failed on CT (Linux?) due to case-sensitive difference between `standardForm` and `standardform` in a couple of `require` statements.  Fixed in above commit.  I'll close after CT verifies that it's OK.

**Comment by pixelzoom** [comment]
CT is happy. Closing.
